spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/manager?characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /manager